# Generated by Django 3.1.7 on 2021-04-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('direccion', models.CharField(default='direccion', max_length=100)),
            ],
            options={
                'db_table': 'datosclientes',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_orden', models.IntegerField()),
                ('fechain', models.CharField(default='', max_length=30)),
                ('fechaout', models.CharField(default='', max_length=30)),
                ('instrumento', models.CharField(default='', max_length=30)),
                ('marca', models.CharField(max_length=20)),
                ('referencia', models.CharField(default='', max_length=30)),
                ('serial', models.CharField(default='', max_length=15)),
                ('encargado', models.CharField(default='', max_length=50)),
                ('abono', models.CharField(default='', max_length=15)),
                ('procesos', models.TextField(default='')),
            ],
            options={
                'db_table': 'datos_ordenes',
            },
        ),
    ]
