# Generated by Django 3.2.6 on 2021-08-22 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('direccion', models.CharField(default='direccion', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_orden', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('fechain', models.DateField(blank=True, null=True)),
                ('fechaout', models.DateField(blank=True, null=True)),
                ('instrumento', models.CharField(default='', max_length=30)),
                ('marca', models.CharField(max_length=20)),
                ('referencia', models.CharField(default='', max_length=30)),
                ('serial', models.CharField(default='', max_length=15)),
                ('encargado', models.CharField(default='', max_length=50)),
                ('abono', models.CharField(default='', max_length=15)),
                ('estado', models.CharField(choices=[('En proceso', 'En proceso'), ('Entregado', 'Entregado')], default='En proceso', max_length=50, null=True)),
                ('cuerdas', models.CharField(default='', max_length=50)),
                ('cero8', models.BooleanField(default=False)),
                ('cero9', models.BooleanField(default=False)),
                ('cero10', models.BooleanField(default=False)),
                ('cero11', models.BooleanField(default=False)),
                ('cero12', models.BooleanField(default=False)),
                ('lastrajo', models.BooleanField(default=False)),
                ('afinacion', models.CharField(default='', max_length=50)),
                ('pfijo', models.BooleanField(default=False)),
                ('pflotante', models.BooleanField(default=False)),
                ('elac', models.BooleanField(default=False)),
                ('acustica', models.BooleanField(default=False)),
                ('bajo', models.BooleanField(default=False)),
                ('teclado', models.BooleanField(default=False)),
                ('vientos', models.BooleanField(default=False)),
                ('percusion', models.BooleanField(default=False)),
                ('pedal', models.BooleanField(default=False)),
                ('amplificador', models.BooleanField(default=False)),
                ('otro', models.CharField(default='', max_length=50, null=True)),
                ('negativo', models.BooleanField(default=False)),
                ('afirmativo', models.BooleanField(default=False)),
                ('lona', models.BooleanField(default=False)),
                ('semi', models.BooleanField(default=False)),
                ('duro', models.BooleanField(default=False)),
                ('caja', models.BooleanField(default=False)),
                ('client', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='client', to='clientesapp.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Valores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.IntegerField(default='', max_length=20)),
                ('show_ref', models.CharField(default='', max_length=1)),
                ('refer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='refer', to='clientesapp.orden')),
            ],
        ),
        migrations.CreateModel(
            name='Procesos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.TextField()),
                ('reference', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reference', to='clientesapp.orden')),
            ],
        ),
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(default='', max_length=50)),
                ('orden_ref', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='orden_ref', to='clientesapp.orden')),
            ],
        ),
    ]
