# Generated by Django 3.2.6 on 2021-08-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fechain',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
