# Generated by Django 3.1.7 on 2021-06-24 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='acustica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orden',
            name='afinacion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='orden',
            name='afirmativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orden',
            name='amplificador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orden',
            name='bajo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orden',
            name='caja',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orden',
            name='cero10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orden',
            name='cero11',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orden',
            name='cero12',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orden',
            name='cero8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orden',
            name='cero9',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orden',
            name='client',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='client', to='clientesapp.cliente'),
        ),
        migrations.AddField(
            model_name='orden',
            name='cuerdas',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='orden',
            name='duro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orden',
            name='elac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('En espera', 'En espera'), ('En proceso', 'En proceso'), ('Terminado', 'Terminado'), ('Entregado', 'Entregado')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='lastrajo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orden',
            name='lona',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orden',
            name='negativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orden',
            name='otro',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='pedal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orden',
            name='percusion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orden',
            name='pfijo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orden',
            name='pflotante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orden',
            name='semi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orden',
            name='teclado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orden',
            name='vientos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orden',
            name='fechain',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='fechaout',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='num_orden',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterModelTable(
            name='cliente',
            table=None,
        ),
        migrations.AlterModelTable(
            name='orden',
            table=None,
        ),
    ]
