# Generated by Django 3.2.6 on 2021-08-27 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientesapp', '0002_alter_orden_fechain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('ref_guia', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ref_guia', to='clientesapp.orden')),
            ],
        ),
    ]
