# Generated by Django 3.1.7 on 2021-06-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientesapp', '0003_auto_20210626_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('En proceso', 'En proceso'), ('Entregado', 'Entregado')], default='En proceso', max_length=50, null=True),
        ),
    ]
