# Generated by Django 3.2.6 on 2021-09-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientesapp', '0003_imagenes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='abono',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='afinacion',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='cuerdas',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='otro',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
