# Generated by Django 3.2.5 on 2021-07-10 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientesapp', '0004_auto_20210626_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='procesos',
        ),
        migrations.CreateModel(
            name='Procesos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.TextField(default='')),
                ('items', models.CharField(default='', max_length=100, null=True)),
                ('reference', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reference', to='clientesapp.orden')),
            ],
        ),
    ]
