# Generated by Django 3.2.5 on 2021-07-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientesapp', '0005_auto_20210710_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procesos',
            name='items',
        ),
        migrations.AlterField(
            model_name='procesos',
            name='process',
            field=models.TextField(),
        ),
    ]
