# Generated by Django 3.2.5 on 2021-08-04 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientesapp', '0006_auto_20210713_0424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.IntegerField(default='', max_length=20)),
                ('refer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='refer', to='clientesapp.orden')),
            ],
        ),
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(default='', max_length=50)),
                ('orden_ref', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='orden_ref', to='clientesapp.orden')),
            ],
        ),
    ]
